import {
    Activity,
    Brain,
    CheckCircle2,
    ClipboardList,
    ShieldCheck,
} from "lucide-react";

import { useAssessment } from "../../contexts/AssessmentContext";

const AssessmentResults = () => {

    const {
        assessmentResult,
        nextStep,

    } = useAssessment();

    if (!assessmentResult) {
        return (
            <div className="text-center py-20">
                <h2 className="text-3xl font-bold text-red-600">
                    Assessment Result Not Found
                </h2>
                <p className="mt-4 text-slate-600">
                    Please complete the handwriting assessment first.
                </p>
            </div>
        );
    }

    const {
        classification,
        evaluations,
        therapyRecommendation,
        summary,
    } = assessmentResult;

    const evaluationCards = [
        {
            title: "Stroke Control",
            data: evaluations.strokeControl,
        },
        {
            title: "Movement Fluency",
            data: evaluations.movementFluency,
        },
        {
            title: "Workspace",
            data: evaluations.workspace,
        },
        {
            title: "Writing Efficiency",
            data: evaluations.writingEfficiency,
        },
    ];

    return (

        <div className="max-w-7xl mx-auto space-y-10">

            {/* ====================================================== */}
            {/* Overall Assessment */}
            {/* ====================================================== */}
            <div className="bg-white rounded-3xl shadow-lg border p-10">
                <div className="flex items-center gap-4">
                    <Brain
                        size={42}
                        className="text-[#9b4c00]"
                    />
                    <div>
                        <h1 className="text-4xl font-bold text-[#9b4c00]">
                            Assessment Results
                        </h1>
                        <p className="text-slate-500 mt-1">
                            Automated handwriting assessment generated by KineWrite.
                        </p>
                    </div>
                </div>

                <div className="grid md:grid-cols-3 gap-8 mt-10">
                    <div className="rounded-2xl bg-orange-50 p-8 border border-orange-200">
                        <p className="text-sm text-slate-500">
                            Overall Score
                        </p>
                        <h2 className="text-5xl font-bold text-[#9b4c00] mt-3">
                            {classification.overallScore}%
                        </h2>
                    </div>

                    <div className="rounded-2xl bg-blue-50 p-8 border border-blue-200">
                        <p className="text-sm text-slate-500">
                            Classification
                        </p>
                        <h2 className="text-3xl font-bold text-blue-700 mt-3">
                            {classification.severity}
                        </h2>
                    </div>

                    <div className="rounded-2xl bg-green-50 p-8 border border-green-200">
                        <p className="text-sm text-slate-500">
                            Confidence
                        </p>
                        <h2 className="text-5xl font-bold text-green-700 mt-3">
                            {classification.confidence}%
                        </h2>
                    </div>
                </div>
            </div>

            {/* ====================================================== */}
            {/* Evaluation Breakdown */}
            {/* ====================================================== */}
            <div className="bg-white rounded-3xl shadow-lg border p-10">
                <div className="flex items-center gap-3 mb-8">
                    <Activity
                        className="text-[#9b4c00]"
                    />
                    <h2 className="text-3xl font-bold text-[#9b4c00]">
                        Evaluation Breakdown
                    </h2>
                </div>

                <div className="grid lg:grid-cols-2 gap-6">
                    {
                        evaluationCards.map((item) => (

                            <div
                                key={item.title}
                                className="rounded-2xl border p-6"
                            >
                                <div className="flex justify-between items-center">
                                    <h3 className="text-2xl font-bold">
                                        {item.title}
                                    </h3>
                                    <span className="font-bold text-[#9b4c00] text-2xl">
                                        {item.data.score}%
                                    </span>
                                </div>

                                <p className="mt-3 font-semibold text-slate-700">
                                    {item.data.level}
                                </p>

                                <ul className="mt-4 space-y-2">
                                    {
                                        item.data.remarks.map((remark, index) => (
                                            <li
                                                key={index}
                                                className="flex gap-2 text-slate-600"
                                            >
                                                <CheckCircle2
                                                    size={18}
                                                    className="text-green-600 mt-1"
                                                />
                                                {remark}
                                            </li>
                                        ))
                                    }
                                </ul>
                            </div>
                        ))
                    }
                </div>
            </div>

            {/* ====================================================== */}
            {/* Therapy Recommendation */}
            {/* ====================================================== */}
            <div className="bg-white rounded-3xl shadow-lg border p-10">
                <div className="flex items-center gap-3 mb-8">
                    <ShieldCheck
                        className="text-[#9b4c00]"
                    />
                    <h2 className="text-3xl font-bold text-[#9b4c00]">
                        Therapy Recommendation
                    </h2>
                </div>

                <div className="grid md:grid-cols-3 gap-8">
                    <div>
                        <p className="text-slate-500">
                            Exercise Level
                        </p>
                        <h3 className="text-4xl font-bold mt-2">
                            Level {therapyRecommendation.exerciseLevel}
                        </h3>
                    </div>

                    <div>
                        <p className="text-slate-500">
                            Session Duration
                        </p>
                        <h3 className="text-4xl font-bold mt-2">
                            {therapyRecommendation.sessionDuration} min
                        </h3>
                    </div>

                    <div>
                        <p className="text-slate-500">
                            Weekly Frequency
                        </p>
                        <h3 className="text-4xl font-bold mt-2">
                            {therapyRecommendation.weeklyFrequency}x
                        </h3>
                    </div>
                </div>

                <div className="mt-8">
                    <p className="font-semibold">
                        Focus Areas
                    </p>

                    <div className="flex flex-wrap gap-3 mt-3">
                        {
                            therapyRecommendation.focusAreas.map((area) => (
                                <span
                                    key={area}
                                    className="px-4 py-2 rounded-full bg-orange-100 text-[#9b4c00] font-semibold"
                                >
                                    {area}
                                </span>
                            ))
                        }
                    </div>
                </div>
            </div>

            {/* ====================================================== */}
            {/* Summary */}
            {/* ====================================================== */}
            <div className="bg-white rounded-3xl shadow-lg border p-10">

                <div className="flex items-center gap-3 mb-6">
                    <ClipboardList
                        className="text-[#9b4c00]"
                    />
                    <h2 className="text-3xl font-bold text-[#9b4c00]">
                        Assessment Summary
                    </h2>
                </div>

                <p className="leading-8 text-lg text-slate-700">
                    {summary}
                </p>
            </div>

            {/* ====================================================== */}
            {/* Continue */}
            {/* ====================================================== */}
            <div className="flex justify-end">
                <button
                    onClick={nextStep}
                    className="px-8 py-4 rounded-2xl bg-[#9b4c00] text-white font-bold hover:bg-[#7b3b00] transition"
                >
                    Continue to Therapist Remarks
                </button>
            </div>
        </div>
    );
};

export default AssessmentResults;