import {
    Brain,
    CheckCircle2,
    ClipboardList,
    Dumbbell,
    Sparkles,
} from "lucide-react";

import AssessmentHeader from "../components/AssessmentHeader";
import AssessmentToolbar from "../components/AssessmentToolbar";

import { useAssessment } from "../utils/AssessmentContext";

const GenerateExercisePlan = () => {

    const {

        analysis,

        remarks,

    } = useAssessment();

    // Temporary exercise plan.
    // Later this will be generated by the backend.

    const exercisePlan = [

        {
            title: "Letter Formation",
            description:
                "Practice tracing uppercase and lowercase letters.",
        },

        {
            title: "Word Spacing",
            description:
                "Improve spacing between letters and words.",
        },

        {
            title: "Stroke Control",
            description:
                "Perform guided stroke exercises using straight and curved lines.",
        },

        {
            title: "Line Control",
            description:
                "Write words while maintaining proper alignment on writing lines.",
        },

        {
            title: "Word Copying",
            description:
                "Copy complete words using proper handwriting techniques.",
        },

    ];

    const handleStartExercises = () => {

        // TODO:
        // Save assessment
        // Save exercise plan
        // Navigate to Exercise Module

        console.log(
            "Start Exercise Plan"
        );

    };

    return (

        <div
            className="
                max-w-6xl
                mx-auto
            "
        >

            <AssessmentHeader

                title="Personalized Exercise Plan"

                subtitle="KineWrite has generated the recommended handwriting intervention program."

            />

            {/* ===================================== */}
            {/* Summary */}
            {/* ===================================== */}

            <div
                className="
                    mt-8

                    bg-blue-50

                    border

                    border-blue-200

                    rounded-3xl

                    p-8
                "
            >

                <div
                    className="
                        flex
                        items-center
                        gap-4
                    "
                >

                    <Brain
                        className="
                            text-blue-600
                        "
                    />

                    <div>

                        <h2
                            className="
                                text-2xl
                                font-bold
                            "
                        >
                            Assessment Summary
                        </h2>

                        <p
                            className="
                                mt-2

                                text-slate-600
                            "
                        >
                            Based on the handwriting assessment,
                            KineWrite recommends focusing on the
                            following handwriting skills.
                        </p>

                    </div>

                </div>

            </div>

            {/* ===================================== */}
            {/* Recommended Exercises */}
            {/* ===================================== */}

            <div
                className="
                    mt-8

                    grid

                    gap-5
                "
            >

                {

                    exercisePlan.map(

                        (exercise) => (

                            <div
                                key={exercise.title}
                                className="
                                    bg-white

                                    rounded-3xl

                                    shadow-lg

                                    p-7

                                    flex

                                    items-start

                                    gap-5
                                "
                            >

                                <div
                                    className="
                                        w-14
                                        h-14

                                        rounded-full

                                        bg-orange-100

                                        flex

                                        items-center

                                        justify-center
                                    "
                                >

                                    <Dumbbell
                                        className="
                                            text-[#9b4c00]
                                        "
                                    />

                                </div>

                                <div
                                    className="
                                        flex-1
                                    "
                                >

                                    <h3
                                        className="
                                            text-xl

                                            font-bold
                                        "
                                    >
                                        {exercise.title}
                                    </h3>

                                    <p
                                        className="
                                            mt-2

                                            text-slate-600
                                        "
                                    >
                                        {exercise.description}
                                    </p>

                                </div>

                                <CheckCircle2
                                    className="
                                        text-green-600
                                    "
                                />

                            </div>

                        )

                    )

                }

            </div>

            {/* ===================================== */}
            {/* Therapist Notes */}
            {/* ===================================== */}

            {

                remarks && (

                    <div
                        className="
                            mt-8

                            bg-yellow-50

                            border

                            border-yellow-200

                            rounded-3xl

                            p-8
                        "
                    >

                        <div
                            className="
                                flex

                                items-center

                                gap-3

                                mb-4
                            "
                        >

                            <ClipboardList
                                className="
                                    text-yellow-600
                                "
                            />

                            <h2
                                className="
                                    text-xl

                                    font-bold
                                "
                            >
                                Therapist Notes
                            </h2>

                        </div>

                        <p
                            className="
                                text-slate-700

                                leading-8
                            "
                        >
                            {remarks}
                        </p>

                    </div>

                )

            }

            {/* ===================================== */}
            {/* Ready */}
            {/* ===================================== */}

            <div
                className="
                    mt-8

                    rounded-3xl

                    bg-green-50

                    border

                    border-green-200

                    p-8
                "
            >

                <div
                    className="
                        flex

                        items-center

                        gap-4
                    "
                >

                    <Sparkles
                        className="
                            text-green-600
                        "
                    />

                    <div>

                        <h3
                            className="
                                text-2xl

                                font-bold
                            "
                        >
                            Exercise Plan Ready
                        </h3>

                        <p
                            className="
                                mt-2

                                text-slate-600
                            "
                        >
                            The student's personalized handwriting
                            intervention program is ready to begin.
                        </p>

                    </div>

                </div>

            </div>

            <AssessmentToolbar

                backLabel="Complete Assessment"

                nextLabel="Start Exercises"

                onBack={() => {

                    window.history.back();

                }}

                onNext={handleStartExercises}

            />

        </div>

    );

};

export default GenerateExercisePlan;